### ISSUE TITLE
[ Known Outside Issues / Bugs ]  Issues that come from either a Server error or outside error from another project

### ISSUE THREAD

**Issue by Adammatthiesen** [withstudiocms/studiocms#69]
This issue is a collection of Known issues and/or Un-fixable issues/bugs that have cropped up due to outside sources such as software or server hardware!

# Ongoing Issues

## `Network Error 500` / `Internal Server Error` / `TypeError: fech failed` / `ENETUNREACH`:

This is the first and primary error that had delayed the progress of StudioCMS for quite a while! It can be caused by both a server being offline / Or even be a result of a server being "corrupted" (see [Astro Lounge Discord: #studio](https://discord.com/channels/830184174198718474/1220126435256041533/1234158992000024716) )

1. This issue can be caused by either [Fly.io](https://status.flyio.net/) or [Turso DB](https://status.turso.tech/) having server connection errors, both of these services are used by [`Astro Studio`](https://studio.astro.build) which acts as the Database and the primary focus of this project.
2. The Terminal errors are not obvious to the fact that the error is a connection to these services, it took many cases where the timing matched up and was in the same region as the Database was deployed to and a matching deployment of the StudioCMS Playground was connected to consecutively.
3. A few examples of this is shown below: (Taken from the `StudioCMS Node Playground` Running on a Coolify.io Host)

```
// EXAMPLE 1
There was an uncaught error in the middle of the stream while rendering /. TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11372:11)
    at async safeFetch (file:///app/node_modules/.pnpm/@astrojs+db@0.11.0/node_modules/@astrojs/db/dist/runtime/utils.js:6:20)
    at async queries.map.sql.sql (file:///app/node_modules/.pnpm/@astrojs+db@0.11.0/node_modules/@astrojs/db/dist/runtime/db-client.js:38:19)
    at async RemotePreparedQuery.all (file:///app/node_modules/.pnpm/drizzle-orm@0.30.9_@libsql+client@0.6.0/node_modules/drizzle-orm/sqlite-proxy/session.js:121:22)
    at async file:///app/playgrounds/node/dist/server/chunks/pages/404_CbtrekdT.mjs:32:23 {
  cause: _SocketError: other side closed
      at TLSSocket.onSocketEnd (node:internal/deps/undici/undici:7998:26)
      at TLSSocket.emit (node:events:526:35)
      at endReadableNT (node:internal/streams/readable:1408:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
    code: 'UND_ERR_SOCKET',
    socket: {
      localAddress: '172.18.0.14',
      localPort: 41398,
      remoteAddress: 'ADDRESS_REDACTED',
      remotePort: 443,
      remoteFamily: 'IPv4',
      timeout: undefined,
      bytesWritten: 892,
      bytesRead: 572
    }
  }
}
```

```
// EXAMPLE 2
16:32:20 [ERROR] Astro DB Error: request to https://ADDRESS_REDACTED-astro.turso.io/v2/pipeline failed, reason: connect ENETUNREACH ADDRESS_REDACTED:443
    at parseRemoteError (file:///app/node_modules/.pnpm/@astrojs+db@0.10.6/node_modules/@astrojs/db/dist/runtime/db-client.js:143:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///app/node_modules/.pnpm/@astrojs+db@0.10.6/node_modules/@astrojs/db/dist/runtime/db-client.js:49:17
    at async safeFetch (file:///app/node_modules/.pnpm/@astrojs+db@0.10.6/node_modules/@astrojs/db/dist/runtime/utils.js:8:5)
    at async queries.map.sql.sql (file:///app/node_modules/.pnpm/@astrojs+db@0.10.6/node_modules/@astrojs/db/dist/runtime/db-client.js:38:19)
    at async RemotePreparedQuery.all (file:///app/node_modules/.pnpm/drizzle-orm@0.30.9_@libsql+client@0.6.0/node_modules/drizzle-orm/sqlite-proxy/session.js:121:22)
    at async file:///app/playground/dist/server/chunks/pages/index_DuLzQIbk.mjs:101:23
    at async callComponentAsTemplateResultOrResponse (file:///app/playground/dist/server/chunks/astro_2nN6mkEX.mjs:1487:25)
    at async renderToAsyncIterable (file:///app/playground/dist/server/chunks/astro_2nN6mkEX.mjs:1515:26)
    at async renderPage (file:///app/playground/dist/server/chunks/astro_2nN6mkEX.mjs:2212:24)
```

### Update: There has been work done that has made these errors occur less often.  But they may still be reported from time to time

# Resolved Issues

### Original Issue: 
_The error mentioned in this comment is related to the reason [This Line](https://github.com/astrolicious/studiocms/blob/8cca3c8748df34621f75b0157d827ef804319b54/packages/studioCMS/src/integrations/studioCMSDashboard/routes/dashboard/layouts/Layout.astro#L51) is commented out and View Transitions are disabled on the dashboard.  This issue is a interesting one where the conditional of `includeViewTransitions` is set to `false` but the `<ViewTransitions />` is still being applied. As well as non of the form function continue to work while View Transitions are enabled._

### Resolution: 
This issue has been resolved by implementation of the new [Zero JS View Transitions](https://astro.build/blog/future-of-astro-zero-js-view-transitions/) and has been added to replace the astro version in our config, this can be seen [Here (From Line 47-53)](https://github.com/astrolicious/studiocms/blob/ebad8d261d84d02cc27b8626028a725f7994ace9/packages/studioCMS/src/integrations/studioCMSDashboard/routes/dashboard/layouts/Layout.astro#L47-L53) and is enabled by a [config option](https://github.com/astrolicious/studiocms/blob/ebad8d261d84d02cc27b8626028a725f7994ace9/playgrounds/node/studiocms.config.mjs#L39)

**Comment by Adammatthiesen** [comment]
Conversations and comments have been limited to Maintainers.  In order for an issue to be brought to this threat, the issue must be considered an External issue! something internal to our project or its configuration should be opened as a separate issue!

**Comment by dreyfus92** [comment]
We should also document the error regarding `<View Transitions />` component and conditional rendering.

**Comment by Adammatthiesen** [comment]
I haven't seen any of these errors caused directly by us since May, so closing this tracker for now.
